@startuml ds - add files
title Sequence Diagram - Add Files for Analysis in Visual Studio Code IDE\nJavaFiles View
skinparam style strictuml

actor User
participant "Add Icon in\nJavaFiles" as CommandPalette
participant ":JavaFileProvider" as JavaFileProvider
participant ":AnalyzeFileProvider" as AnalyzeFileProvider

User -> CommandPalette : Activates "javaFileProvider.addToSendList"
CommandPalette -> JavaFileProvider : Executes the command \n//javaFileProvider.addToSendList(item)//

JavaFileProvider -> JavaFileProvider : javaItems = collectJavaFiles(item.ui.fsPath)

alt item is an instance of Directory
    JavaFileProvider -> JavaFileProvider : collectJavaFiles(item.uri) recursively

    JavaFileProvider -> "javaFiles\n:JavaItem[]" as javaFiles **

participant "itemsMap\n:Map<filepath, JavaItem>" as itemsMap
participant "analyzeList\n:Map<filepath, JavaItem>" as analyzeList

    loop For each Java file in the folder
        JavaFileProvider -> JavaFileProvider : Read the file content
        JavaFileProvider -> AnalyzeFileProvider: addFileToAnalyze(javaItem)
    end
else item is an instance of File with the .java extension
    JavaFileProvider -> itemsMap : javaItem = get(javaItem.filepath)
    JavaFileProvider -> javaFiles : push(javaItem)
end

loop For each javaItem in JavaItems
    JavaFileProvider -> AnalyzeFileProvider : addFileToAnalyze(javaItem)

    JavaFileProvider -> analyzeList : has(javaItem.filePath)
    alt If analyzeList contains javaItem
        JavaFileProvider -> analyzeList : set(javaItem.filepath, javaItem)
    end
end

JavaFileProvider -> JavaFileProvider: refresh()

<-- JavaFileProvider : The analyzeFilesView updates to display the added files
@enduml

