name: Analyze Logs in Zookeper PR

on:
 repository_dispatch:
    types: [zookeeper_pr_analysis]

jobs:
  analyze-logs:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Log Density code
        uses: actions/checkout@v4
        with:   
          fetch-depth: 0  # Important pour récupérer l'historique complet


      - name: Checkout Zookeeper PR Code
        run: |
          if [ -d "services/training_data/Zookeeper" ]; then
            cd services/training_data/Zookeeper
            git fetch origin pull/${{ github.event.client_payload.pr_number }}/head:pr-branch
            git checkout pr-branch
          else
            echo "Zookeeper repo not found in training_data"
            exit 1
          fi

      - name: Install Docker Compose (if missing)
        shell: powershell
        run: |
          if (-not (Get-Command docker-compose -ErrorAction SilentlyContinue)) {
            choco install docker-compose
          }

          - name: Extract Java Log Statements
          shell: bash
          run: |
            log_file="logs_extracted.txt"
            echo "" > $log_file
  
            while read -r file; do
              if [ -f "services/training_data/Zookeeper/$file" ]; then
                echo "Processing $file..."
                grep -E 'LOG\.(info|debug|warn|error)\(.*?\)|System\.out\.println\(.*?\)' "training_data/Zookeeper/$file" >> $log_file
              fi
            done < changed_java_files.txt
  
            cat $log_file

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Start Ollama with Docker Compose
        run: docker-compose -f services/docker-compose.yml up -d

      - name: Wait for Ollama to start
        run: sleep 10  # Ajuste si nécessaire

      - name: Run Ollama Query
        run: node logdensitytool/src/services/apiModel/queryOllama.js
        